LOCK TABLE ATOM_FEED WRITE;
LOCK TABLE ATOM_ENTRY WRITE;
LOCK TABLE ATOM_CATEGORY WRITE;
LOCK TABLE ATOM_LINK WRITE;

DELETE FROM ATOM_LINK;
DELETE FROM ATOM_CATEGORY;
DELETE FROM ATOM_ENTRY;
DELETE FROM ATOM_FEED;

INSERT INTO ATOM_FEED (FEED_ID) VALUES (1);
